package com.agentic.browser.agent

object DomSimplifierPayload {
    const val BRIDGE_NAME = "AgentBridge"
    // Security boundary: this payload exposes only fixed helper functions consumed by CommandExecutor.
    // Raw model strings are never interpolated into this JavaScript source.
    fun build(): String = """
(function(){try{
 if(window.__agenticBrowserInstalled===true){window.__agenticExtractDom&&window.__agenticExtractDom();return;}
 window.__agenticBrowserInstalled=true;window.__agenticElementMap=new Map();window.__agenticDomPaused=false;window.__agenticDomTick=null;
 function visible(el){if(!el)return false;const s=getComputedStyle(el);if(!s||s.display==='none'||s.visibility==='hidden'||s.opacity==='0')return false;const r=el.getBoundingClientRect();return r.width>0&&r.height>0;}
 function clean(t){return (t||'').replace(/\s+/g,' ').replace(/[\u0000-\u001F\u007F]/g,'').trim().slice(0,120);}
 function label(el){return clean(el.getAttribute('aria-label'))||clean(el.getAttribute('title'))||clean(el.getAttribute('placeholder'))||clean(el.innerText||el.textContent)||clean(el.getAttribute('name'))||clean(el.getAttribute('id'))||'unlabeled';}
 function role(el){const tag=(el.tagName||'').toLowerCase();const type=(el.getAttribute('type')||'').toLowerCase();const r=(el.getAttribute('role')||'').toLowerCase();if(tag==='input'){if(['submit','button','reset'].includes(type))return 'Button';if(type==='password')return 'PasswordInput';if(type==='search')return 'SearchInput';return 'Input';}if(tag==='textarea')return 'TextArea';if(tag==='select')return 'Select';if(tag==='button'||r==='button')return 'Button';if(tag==='a'||r==='link')return 'Link';if(r==='textbox')return 'Input';return 'Interactive';}
 function interactive(el){if(!el||!visible(el)||el.disabled||el.getAttribute('aria-disabled')==='true')return false;const tag=(el.tagName||'').toLowerCase();const r=(el.getAttribute('role')||'').toLowerCase();return ['button','a','input','textarea','select'].includes(tag)||['button','link','textbox','checkbox','radio','combobox','menuitem'].includes(r)||!!el.onclick||el.tabIndex>=0;}
 function path(el){if(el.id)return '#'+CSS.escape(el.id);const p=[];let n=el;while(n&&n.nodeType===1&&n!==document.body&&p.length<5){let x=n.nodeName.toLowerCase();const parent=n.parentNode;if(parent){const sib=Array.from(parent.children).filter(e=>e.nodeName===n.nodeName);if(sib.length>1)x+=':nth-of-type('+(sib.indexOf(n)+1)+')';}p.unshift(x);n=n.parentElement;}return p.join(' > ');}
 function assign(el,id){const domId='agentic_element_'+id;el.setAttribute('data-agent-id',String(id));if(!el.id)el.id=domId;window.__agenticElementMap.set(String(id),{id:String(id),domId:el.id,selector:path(el),tag:(el.tagName||'').toLowerCase()});}
 window.__agenticExtractDom=function(){const nodes=Array.from(document.querySelectorAll('a,button,input,textarea,select,[role],[onclick],[tabindex]'));const rows=[];window.__agenticElementMap.clear();let id=1;for(const el of nodes){if(!interactive(el))continue;if(id>120)break;assign(el,id);rows.push('[ID:'+id+'] '+role(el)+': '+label(el));id++;}const payload=rows.join(' | ');if(window.$BRIDGE_NAME&&window.$BRIDGE_NAME.onDomExtracted&&!window.__agenticDomPaused)window.$BRIDGE_NAME.onDomExtracted(payload);return payload;};
 window.__agenticPauseDomUpdates=function(){window.__agenticDomPaused=true;return JSON.stringify({ok:true,action:'pause_dom'});};
 window.__agenticResumeDomUpdates=function(){window.__agenticDomPaused=false;const payload=window.__agenticExtractDom();return JSON.stringify({ok:true,action:'resume_dom',dom:payload?payload.slice(0,240):''});};
 window.__agenticScheduleExtract=function(){if(window.__agenticDomPaused)return;if(window.__agenticDomTick)return;window.__agenticDomTick=setTimeout(function(){window.__agenticDomTick=null;window.__agenticExtractDom();},350);};
 window.__agenticClick=function(id){const m=window.__agenticElementMap.get(String(id));let el=null;if(m&&m.domId)el=document.getElementById(m.domId);if(!el&&m&&m.selector)el=document.querySelector(m.selector);if(!el)el=document.querySelector('[data-agent-id="'+String(id)+'"]');if(!el)return JSON.stringify({ok:false,error:'Element not found',id:String(id)});el.scrollIntoView({behavior:'smooth',block:'center'});el.focus&&el.focus();el.click();return JSON.stringify({ok:true,action:'click',id:String(id)});};
 window.__agenticInputText=function(id,text){const m=window.__agenticElementMap.get(String(id));let el=null;if(m&&m.domId)el=document.getElementById(m.domId);if(!el&&m&&m.selector)el=document.querySelector(m.selector);if(!el)el=document.querySelector('[data-agent-id="'+String(id)+'"]');if(!el)return JSON.stringify({ok:false,error:'Element not found',id:String(id)});el.scrollIntoView({behavior:'smooth',block:'center'});el.focus&&el.focus();el.value=String(text||'');el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));return JSON.stringify({ok:true,action:'input_text',id:String(id)});};
 window.__agenticSubmitForm=function(id){const m=window.__agenticElementMap.get(String(id));let el=null;if(m&&m.domId)el=document.getElementById(m.domId);if(!el&&m&&m.selector)el=document.querySelector(m.selector);if(!el)el=document.querySelector('[data-agent-id="'+String(id)+'"]');if(!el)return JSON.stringify({ok:false,error:'Element not found',id:String(id)});const form=el.form||(el.tagName&&el.tagName.toLowerCase()==='form'?el:null);if(form&&form.requestSubmit){form.requestSubmit();return JSON.stringify({ok:true,action:'submit_form',id:String(id)});}if(form&&form.submit){form.submit();return JSON.stringify({ok:true,action:'submit_form',id:String(id)});}el.click&&el.click();return JSON.stringify({ok:true,action:'submit_form',id:String(id)});};
 window.__agenticScroll=function(direction){const dir=String(direction||'down').toLowerCase()==='up'?'up':'down';const delta=dir==='up'?-700:700;window.scrollBy({top:delta,left:0,behavior:'smooth'});return JSON.stringify({ok:true,action:'scroll',direction:dir});};
 window.__agenticExtractData=function(id,keyName){const m=window.__agenticElementMap.get(String(id));let el=null;if(m&&m.domId)el=document.getElementById(m.domId);if(!el&&m&&m.selector)el=document.querySelector(m.selector);if(!el)el=document.querySelector('[data-agent-id="'+String(id)+'"]');if(!el)return JSON.stringify({ok:false,error:'Element not found',id:String(id)});const text=(el.innerText||el.textContent||el.value||'').replace(/\s+/g,' ').trim().slice(0,2000);if(!text)return JSON.stringify({ok:false,error:'Extracted value is empty',id:String(id)});return JSON.stringify({ok:true,action:'extract_data',id:String(id),key_name:String(keyName||'').slice(0,64),value:text});};
 if(!window.__agenticObserver){window.__agenticObserver=new MutationObserver(function(){window.__agenticScheduleExtract();});window.__agenticObserver.observe(document.documentElement||document.body,{subtree:true,childList:true,characterData:true,attributes:true});}
 window.__agenticExtractDom();
}catch(e){if(window.$BRIDGE_NAME&&window.$BRIDGE_NAME.onDomError)window.$BRIDGE_NAME.onDomError(String(e&&e.message?e.message:e));}})();
""".trimIndent()
}
